// <auto-generated />
using System;
using System.Text.Json;
using APTM.Gate.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APTM.Gate.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GateDbContext))]
    [Migration("20260413100418_DenormalizeCandidateInfoInProcessedEvents")]
    partial class DenormalizeCandidateInfoInProcessedEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("APTM.Gate.Infrastructure.Entities.AcceptedTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("label");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("idx_accepted_tokens_token");

                    b.ToTable("accepted_tokens", (string)null);
                });

            modelBuilder.Entity("APTM.Gate.Infrastructure.Entities.CandidateEntity", b =>
                {
                    b.Property<Guid>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<int>("CandidateTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("candidate_type_id");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("gender");

                    b.Property<int?>("JacketNumber")
                        .HasColumnType("integer")
                        .HasColumnName("jacket_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ServiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("service_number");

                    b.HasKey("CandidateId");

                    b.ToTable("candidates", (string)null);
                });

            modelBuilder.Entity("APTM.Gate.Infrastructure.Entities.CheckpointConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("CheckpointName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("checkpoint_name");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("route_name");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.HasKey("Id");

                    b.ToTable("checkpoint_config", (string)null);
                });

            modelBuilder.Entity("APTM.Gate.Infrastructure.Entities.GateConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActiveEventId")
                        .HasColumnType("integer")
                        .HasColumnName("active_event_id");

                    b.Property<string>("ActiveEventName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("active_event_name");

                    b.Property<int?>("CheckpointSequence")
                        .HasColumnType("integer")
                        .HasColumnName("checkpoint_sequence");

                    b.Property<int>("ClockOffsetMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("clock_offset_ms");

                    b.Property<int>("DataSnapshotVersion")
                        .HasColumnType("integer")
                        .HasColumnName("data_snapshot_version");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("device_code");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("GateRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gate_role");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_date");

                    b.Property<Guid>("TestInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_instance_id");

                    b.Property<string>("TestInstanceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("test_instance_name");

                    b.HasKey("Id");

                    b.ToTable("gate_config", (string)null);
                });

            modelBuilder.Entity("APTM.Gate.Infrastructure.Entities.ProcessedEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<string>("CandidateName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("candidate_name");

                    b.Property<int?>("CheckpointSequence")
                        .HasColumnType("integer")
                        .HasColumnName("checkpoint_sequence");

                    b.Property<decimal?>("DurationSeconds")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("duration_seconds");

                    b.Property<int?>("EventId")
                        .HasColumnType("integer")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("event_type");

                    b.Property<int?>("HeatNumber")
                        .HasColumnType("integer")
                        .HasColumnName("heat_number");

                    b.Property<bool>("IsFirstRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_first_read");

                    b.Property<int?>("JacketNumber")
                        .HasColumnType("integer")
                        .HasColumnName("jacket_number");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<long?>("RawBufferId")
                        .HasColumnType("bigint")
                        .HasColumnName("raw_buffer_id");

                    b.Property<DateTimeOffset>("ReadTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_time");

                    b.Property<string>("TagEPC")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tag_epc");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId")
                        .HasDatabaseName("idx_processed_events_candidate");

                    b.HasIndex("EventId")
                        .HasDatabaseName("idx_processed_events_event_id");

                    b.HasIndex("EventType")
                        .HasDatabaseName("idx_processed_events_type");

                    b.HasIndex("RawBufferId");

                    b.ToTable("processed_events", (string)null);
                });

            modelBuilder.Entity("APTM.Gate.Infrastructure.Entities.RaceStartTime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.PrimitiveCollection<Guid[]>("CandidateIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("candidate_ids");

                    b.Property<DateTimeOffset>("GunStartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("gun_start_time");

                    b.Property<Guid>("HeatId")
                        .HasColumnType("uuid")
                        .HasColumnName("heat_id");

                    b.Property<int>("HeatNumber")
                        .HasColumnType("integer")
                        .HasColumnName("heat_number");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<int>("SourceClockOffsetMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("source_clock_offset_ms");

                    b.Property<Guid>("SourceDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_device_id");

                    b.HasKey("Id");

                    b.HasIndex("HeatId")
                        .IsUnique();

                    b.ToTable("race_start_times", (string)null);
                });

            modelBuilder.Entity("APTM.Gate.Infrastructure.Entities.RawTagBuffer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<int?>("AntennaPort")
                        .HasColumnType("integer")
                        .HasColumnName("antenna_port");

                    b.Property<DateTimeOffset>("InsertedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inserted_at");

                    b.Property<bool>("IsDuplicate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_duplicate");

                    b.Property<decimal?>("RSSI")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("rssi");

                    b.Property<DateTimeOffset>("ReadTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("status");

                    b.Property<string>("TagEPC")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tag_epc");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_raw_tag_buffer_status")
                        .HasFilter("status = 'PENDING'");

                    b.ToTable("raw_tag_buffer", (string)null);
                });

            modelBuilder.Entity("APTM.Gate.Infrastructure.Entities.ReceivedSyncData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ClientRecordId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("client_record_id");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("data_type");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("SourceDeviceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_device_code");

                    b.Property<Guid>("SourceDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_device_id");

                    b.HasKey("Id");

                    b.HasIndex("ClientRecordId")
                        .IsUnique()
                        .HasDatabaseName("idx_received_sync_client_record");

                    b.ToTable("received_sync_data", (string)null);
                });

            modelBuilder.Entity("APTM.Gate.Infrastructure.Entities.ScoringStatusEntity", b =>
                {
                    b.Property<int>("ScoringStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("scoring_status_id");

                    b.Property<bool>("IsPassingStatus")
                        .HasColumnType("boolean")
                        .HasColumnName("is_passing_status");

                    b.Property<int>("ScoringTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("scoring_type_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status_code");

                    b.Property<string>("StatusLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("status_label");

                    b.HasKey("ScoringStatusId");

                    b.HasIndex("ScoringTypeId");

                    b.ToTable("scoring_statuses", (string)null);
                });

            modelBuilder.Entity("APTM.Gate.Infrastructure.Entities.ScoringTypeEntity", b =>
                {
                    b.Property<int>("ScoringTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("scoring_type_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("ScoringTypeId");

                    b.ToTable("scoring_types", (string)null);
                });

            modelBuilder.Entity("APTM.Gate.Infrastructure.Entities.SyncLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("LastProcessedEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("last_processed_event_id");

                    b.Property<Guid?>("LastReceivedSyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_received_sync_id");

                    b.Property<DateTimeOffset>("PulledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pulled_at");

                    b.Property<string>("PullerDeviceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("puller_device_code");

                    b.Property<Guid>("PullerDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("puller_device_id");

                    b.HasKey("Id");

                    b.ToTable("sync_log", (string)null);
                });

            modelBuilder.Entity("APTM.Gate.Infrastructure.Entities.TagAssignmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<string>("TagEPC")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tag_epc");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("TagEPC")
                        .IsUnique()
                        .HasDatabaseName("idx_tag_assignments_epc");

                    b.ToTable("tag_assignments", (string)null);
                });

            modelBuilder.Entity("APTM.Gate.Infrastructure.Entities.TestEventEntity", b =>
                {
                    b.Property<int>("TestTypeEventId")
                        .HasColumnType("integer")
                        .HasColumnName("test_type_event_id");

                    b.Property<int>("EventId")
                        .HasColumnType("integer")
                        .HasColumnName("event_id");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_name");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("event_type");

                    b.Property<int?>("ScoringTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("scoring_type_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.HasKey("TestTypeEventId");

                    b.HasIndex("ScoringTypeId");

                    b.ToTable("test_events", (string)null);
                });

            modelBuilder.Entity("APTM.Gate.Infrastructure.Entities.ProcessedEvent", b =>
                {
                    b.HasOne("APTM.Gate.Infrastructure.Entities.CandidateEntity", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APTM.Gate.Infrastructure.Entities.RawTagBuffer", "RawTag")
                        .WithMany()
                        .HasForeignKey("RawBufferId");

                    b.Navigation("Candidate");

                    b.Navigation("RawTag");
                });

            modelBuilder.Entity("APTM.Gate.Infrastructure.Entities.ScoringStatusEntity", b =>
                {
                    b.HasOne("APTM.Gate.Infrastructure.Entities.ScoringTypeEntity", "ScoringType")
                        .WithMany("ScoringStatuses")
                        .HasForeignKey("ScoringTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScoringType");
                });

            modelBuilder.Entity("APTM.Gate.Infrastructure.Entities.TagAssignmentEntity", b =>
                {
                    b.HasOne("APTM.Gate.Infrastructure.Entities.CandidateEntity", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("APTM.Gate.Infrastructure.Entities.TestEventEntity", b =>
                {
                    b.HasOne("APTM.Gate.Infrastructure.Entities.ScoringTypeEntity", "ScoringType")
                        .WithMany()
                        .HasForeignKey("ScoringTypeId");

                    b.Navigation("ScoringType");
                });

            modelBuilder.Entity("APTM.Gate.Infrastructure.Entities.ScoringTypeEntity", b =>
                {
                    b.Navigation("ScoringStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
